/*let testArray = [
    {
      "cover": "https://cdn-images-1.medium.com/fit/c/504/222/1*yTB0AML2PhCGh6iK5eDgbg.jpeg",
      "title": "Warren Buffett’s Recent Explanation of How Money Now Works Is the Most Important in&nbsp;History",
      "summary": "The value of the money you have is changing. “Debt “and what it means is fundamentally changing.",
      "user": "Tim Denning",
      "section": "History",
      "date": "8/24/2020",
      "time": "6",
      "popular": "No",
      "ranking": 50,
      "editorPick": "Si",
      "mediumLink": "https://medium.com/the-ascent/warren-buffetts-recent-explanation-of-how-money-now-works-is-the-most-important-in-history-2e45461a5969"
    },
    {
      "cover": "https://miro.medium.com/max/1600/1*yXMww8gXocJOMXiu2MKA4w.jpeg",
      "title": "This Is How It Happens",
      "summary": "A study of men in Hitler’s Germany shows how people allow tyranny to spread",
      "user": "Colin Horgan",
      "section": "History",
      "date": "8/27/2020",
      "time": "7",
      "popular": "No",
      "ranking": 65,
      "editorPick": "No",
      "mediumLink": "https://medium.com/@cfhorgan/this-is-how-it-happens-c289765df373"
    },
    {
      "cover": "https://miro.medium.com/max/1400/1*Rx_SbkL-bZSDG01lpLmwwg.jpeg",
      "title": "How to Find Grace When School Is at Home",
      "summary": "Your children are your spiritual practice",
      "user": "Lisa Marie",
      "section": "Planet Soul",
      "date": "9/15/2020",
      "time": "8",
      "popular": "No",
      "ranking": 35,
      "editorPick": "No",
      "mediumLink": "https://humanparts.medium.com/how-to-find-grace-when-school-is-at-home-fddfff35f1bc"
    },
    {
      "cover": "https://miro.medium.com/max/700/1*h3uaXRCk3GfLuHBgatpvHQ.jpeg",
      "title": "The Racist Cost of a Pandemic Vacation in the Bahamas",
      "summary": "Is our suffering worth the frolic on the beach and a few Instagram likes?",
      "user": "Alicia Wallace",
      "section": "Momentum",
      "date": "9/15/2020",
      "time": "4",
      "popular": "No",
      "ranking": 750,
      "editorPick": "Si",
      "mediumLink": "https://momentum.medium.com/the-racist-cost-of-a-pandemic-vacation-in-the-bahamas-1d8d7a10b726"
    },
    {
      "cover": "https://miro.medium.com/max/700/1*lAI9mjU5979dD6EbZfL3qw.jpeg",
      "title": "Thousands of People Might Be in Prison for Crimes That Never Even Happened",
      "summary": "Once an event is mislabeled as a crime, forward momentum takes over — especially when there’s already a suspect",
      "user": "Jessica S. Henry",
      "section": "Momentum",
      "date": "9/2/2020",
      "time": "5",
      "popular": "No",
      "ranking": 1100,
      "editorPick": "Si",
      "mediumLink": "https://momentum.medium.com/thousands-of-people-might-be-in-prison-for-crimes-that-never-even-happened-94901a896578"
    },
    {
      "cover": "https://miro.medium.com/max/700/1*K_Vqllq4uxafp_yk1OHJNw.jpeg",
      "title": "Malcolm X’s Daughter on BLM, Sports Activism, and the ‘Right’ Way to Protest",
      "summary": "Ilyasah Shabazz suggests we take her father’s advice and keep pushing for justice",
      "user": "Keith Nelson Jr",
      "section": "Momentum",
      "date": "9/14/2020",
      "time": "5",
      "popular": "No",
      "ranking": 1100,
      "editorPick": "Si",
      "mediumLink": "https://momentum.medium.com/we-must-open-the-doors-and-we-must-see-to-it-they-remain-open-so-that-others-can-pass-through-4f4b73668639"
    },
    {
      "cover": "https://miro.medium.com/max/1500/1*g7EmzhaxrpFWV9fNu2z-DQ.png",
      "title": "An Oral History of Pandemic Life Told by Black Essential Workers",
      "summary": "From grocery store clerks to mental health counselors to mail carriers, Black essential workers describe living during the pandemic",
      "user": "Shanna Loga",
      "section": "Elemental",
      "date": "9/14/2020",
      "time": "29",
      "popular": "No",
      "ranking": 593,
      "editorPick": "No",
      "mediumLink": "https://elemental.medium.com/an-oral-history-of-the-pandemic-told-by-black-essential-workers-d217a59cb5b8"
    },
    {
      "cover": "https://miro.medium.com/max/1000/1*zBJ-Z6TheluV5U_XeFp1JQ.jpeg",
      "title": "Does “Midwest Nice” Breed Racism?",
      "summary": "George Floyd’s murder and Jacob Blake’s shooting happened in the heartland",
      "user": "Shanna Loga",
      "section": "Elemental",
      "date": "9/3/2020",
      "time": "8",
      "popular": "No",
      "ranking": 50,
      "editorPick": "No",
      "mediumLink": "https://medium.com/an-injustice/does-midwest-nice-breed-racism-b9c54aaf6cbf"
    },
    {
      "cover": "https://miro.medium.com/max/700/1*mNMFTXKNmtEhYikz67JU7A.jpeg",
      "title": "Your Teenage Email Account Is a Lost Time Capsule",
      "summary": "If you lose access to virtual memory spaces, some of your memories might go out with it",
      "user": "Angela Lashbrook",
      "section": "Onezero",
      "date": "9/16/2020",
      "time": "7",
      "popular": "No",
      "ranking": 101,
      "editorPick": "No",
      "mediumLink": "https://onezero.medium.com/your-teenage-email-account-is-a-lost-time-capsule-a7627d53c466"
    },
    {
      "cover": "https://miro.medium.com/max/700/1*C4p-WHaVKMs2j1ezb8X2Lg.jpeg",
      "title": "Uber and Lyft’s California Proposal Is a Mishmash of Old Ideas for Fixing the Gig Economy",
      "summary": "The past is our best guide for understanding the future of ride-hailing apps",
      "user": "Sarah Kessler",
      "section": "Onezero",
      "date": "9/16/2020",
      "time": "10",
      "popular": "No",
      "ranking": 145,
      "editorPick": "No",
      "mediumLink": "https://onezero.medium.com/uber-and-lyfts-california-proposal-is-a-mishmash-of-old-ideas-for-fixing-the-gig-economy-c4b007fcfa04"
    },
    {
      "cover": "https://miro.medium.com/max/1000/1*Fd4OqoBw0SuCVajbsc_iug.jpeg",
      "title": "Apple’s Best New Announcement, According to a Developer",
      "summary": "Plus, one unpleasant surprise",
      "user": "Kaya Thomas",
      "section": "Onezero",
      "date": "9/16/2020",
      "time": "3",
      "popular": "No",
      "ranking": 355,
      "editorPick": "No",
      "mediumLink": "https://onezero.medium.com/apples-best-new-announcement-according-to-a-developer-834680d4a634"
    },
    {
      "cover": "https://miro.medium.com/max/700/1*8fJMPGzka_jGULI3O9VoPQ.jpeg",
      "title": "The Apple Watch Is the New Starter Phone",
      "summary": "Apple’s new features bring a new generation of kids into its ecosystem",
      "user": "Dave Gershgorn",
      "section": "Onezero",
      "date": "9/15/2020",
      "time": "3",
      "popular": "No",
      "ranking": 351,
      "editorPick": "No",
      "mediumLink": "https://onezero.medium.com/the-apple-watch-is-the-new-starter-phone-4eb74ed61e0b"
    },
    {
      "cover": "https://miro.medium.com/max/700/1*Qm1D7pAS4R24qrCJG51dlQ.png",
      "title": "The Future Must Be Fixable",
      "summary": "A great device can still be a pain to repair",
      "user": "Damon Beres",
      "section": "Onezero",
      "date": "9/15/2020",
      "time": "3",
      "popular": "No",
      "ranking": 124,
      "editorPick": "No",
      "mediumLink": "https://onezero.medium.com/the-microsoft-surface-duo-is-a-repairability-nightmare-d89b94ade2de"
    },
    {
      "cover": "https://miro.medium.com/max/700/1*swv12dnSAqKY9UeLCxrcfQ.jpeg",
      "title": "Data Privacy Exhaustion Is Real",
      "summary": "Protecting our personal info is a lifestyle choice many of us aren’t making",
      "user": "Simon Pitt",
      "section": "Onezero",
      "date": "9/15/2020",
      "time": "9",
      "popular": "No",
      "ranking": 304,
      "editorPick": "No",
      "mediumLink": "https://onezero.medium.com/data-privacy-exhaustion-is-real-9ca868068f2b"
    },
    {
      "cover": "https://miro.medium.com/max/1000/1*_Boo4YYmPFuzdPmYssGiCg.jpeg",
      "title": "‘My Karen Translator’ Responds to Racism So You Don’t Have To",
      "summary": "The project, which posts some responses on Instagram, intends to shift the burden of explaining racism away from Black people",
      "user": "Hope King",
      "section": "Onezero",
      "date": "9/15/2020",
      "time": "9",
      "popular": "No",
      "ranking": 967,
      "editorPick": "Si",
      "mediumLink": "https://onezero.medium.com/my-karen-translator-responds-to-racism-so-you-don-t-have-to-47d6d8195786"
    },
    {
      "cover": "https://miro.medium.com/max/700/1*ySrRuOkJ8rNgqKQsQnR4Qg.jpeg",
      "title": "USB-C Was Supposed to Simplify Our Lives. Instead, It’s a Total Mess.",
      "summary": "A mix of hidden standards make the ubiquitous cable a pain to deal with",
      "user": "Owen Williams",
      "section": "Onezero",
      "date": "9/14/2020",
      "time": "4",
      "popular": "No",
      "ranking": 1400,
      "editorPick": "Si",
      "mediumLink": "https://onezero.medium.com/usb-c-was-supposed-to-simplify-our-lives-instead-its-a-total-mess-626bb2ea3688"
    },
    {
      "cover": "https://miro.medium.com/max/700/1*NCX0iZWTSOneqohfZU_3vA.jpeg",
      "title": "The Privatized Internet Is Failing Our Kids",
      "summary": "The failure of online schooling highlights a basic flaw in our digital infrastructure: It wasn’t built to supply public goods.",
      "user": "Will Oremus",
      "section": "Onezero",
      "date": "9/12/2020",
      "time": "10",
      "popular": "No",
      "ranking": 350,
      "editorPick": "No",
      "mediumLink": "https://onezero.medium.com/the-travesty-of-remote-learning-is-unfolding-in-real-time-6307975560e8"
    },
    {
      "cover": "https://miro.medium.com/max/700/1*W9-RgQnjkiaXoFtgasceDg.jpeg",
      "title": "Here’s Why Your Phone Can’t Capture California’s Apocalypse Sky",
      "summary": "And what it says about the problems with trusting your smartphone camera",
      "user": "Thomas Smith",
      "section": "Onezero",
      "date": "9/9/2020",
      "time": "7",
      "popular": "No",
      "ranking": 1940,
      "editorPick": "Si",
      "mediumLink": "https://onezero.medium.com/heres-why-your-phone-can-t-capture-california-s-apocalypse-sky-3c98c43b810"
    },
    {
      "cover": "https://miro.medium.com/max/400/1*IdnIp5E6Xur7nCnn-dwdXA.png",
      "title": "We’re Six Months Into the Pandemic. How Do We Get Out?",
      "summary": "Introducing Elemental’s special series on Covid-19",
      "user": "Sarah Collins",
      "section": "Elemental",
      "date": "9/14/2020",
      "time": "1",
      "popular": "No",
      "ranking": 236,
      "editorPick": "No",
      "mediumLink": "https://elemental.medium.com/were-six-months-into-the-pandemic-how-do-we-get-out-739928016eab"
    },
    {
      "cover": "https://miro.medium.com/max/1464/1*wcPmcIKBa8n-t2QTJzEvww.png",
      "title": "The Most Likely Way You’ll Get Infected With Covid-19",
      "summary": "You don’t have to sanitize your apples anymore, but you do have to wear a mask",
      "user": "Dana G Smith",
      "section": "Elemental",
      "date": "9/16/2020",
      "time": "12",
      "popular": "No",
      "ranking": 1960,
      "editorPick": "Si",
      "mediumLink": "https://elemental.medium.com/the-most-likely-way-youll-get-infected-with-covid-19-30430384e5a5"
    },
    {
      "cover": "https://miro.medium.com/max/1500/1*55uHLB1TW0Un7C7fzYsxCg.png",
      "title": "Why More Covid-19 Patients Are Surviving the ICU",
      "summary": "Intensive care has risen to the challenge of 2020. Here’s what has changed.",
      "user": "Chris Baraniuk",
      "section": "Elemental",
      "date": "9/15/2020",
      "time": "8",
      "popular": "No",
      "ranking": 543,
      "editorPick": "No",
      "mediumLink": "https://elemental.medium.com/why-more-covid-19-patients-are-surviving-the-icu-34e05fe9eba7"
    },
    {
      "cover": "https://miro.medium.com/max/1000/1*WiSwL-96mFCzmIOj8LdPlA.png",
      "title": "Inside a New York City ER: Then and Now",
      "summary": "Lessons from the Covid-19 frontlines through the eyes of Dr. Craig Spencer",
      "user": "Wudan Yan",
      "section": "Elemental",
      "date": "9/15/2020",
      "time": "7",
      "popular": "No",
      "ranking": 177,
      "editorPick": "No",
      "mediumLink": "https://elemental.medium.com/what-life-is-like-in-the-er-then-and-now-e05b781eb2c6"
    },
    {
      "cover": "https://miro.medium.com/max/1500/1*iE50-JtJDy_3V4WPDLi6dA.png",
      "title": "This Lawyer Ran Errands for His High-Risk Wife. Then an Epidemiologist Rated His Every Move.",
      "summary": "Real life meets public health advice",
      "user": "Sara Austin",
      "section": "Elemental",
      "date": "9/14/2020",
      "time": "13",
      "popular": "No",
      "ranking": 258,
      "editorPick": "No",
      "mediumLink": "https://elemental.medium.com/this-lawyer-ran-errands-for-his-high-risk-wife-then-an-epidemiologist-rated-his-every-move-f9a926ad96ec"
    },
    {
      "cover": "https://miro.medium.com/max/700/1*keb01Ixbgxirmo6KjSIgWw.jpeg",
      "title": "Can Masks Function as a Crude Vaccine?",
      "summary": "A new theory suggests masks lead to less severe infections that still offer immunity",
      "user": "Dana G Smith",
      "section": "Coronavirus",
      "date": "9/11/2020",
      "time": "7",
      "popular": "No",
      "ranking": 786,
      "editorPick": "Si",
      "mediumLink": "https://coronavirus.medium.com/can-masks-function-as-a-crude-vaccine-696049cb06db"
    },
    {
      "cover": "https://miro.medium.com/max/700/1*td-la5s4MEy0XuyYf847pQ.jpeg",
      "title": "The Most Important Coronavirus News This Week",
      "summary": "",
      "user": "Alexandra Sifferlin",
      "section": "Elemental",
      "date": "9/11/2020",
      "time": "3",
      "popular": "No",
      "ranking": 56,
      "editorPick": "No",
      "mediumLink": "https://elemental.medium.com/the-most-important-coronavirus-news-this-week-e3efe610a2e"
    },
    {
      "cover": "https://miro.medium.com/max/700/1*stJ_IGWH7K4h4P2Vp94ntw.jpeg",
      "title": "5 Lessons the Black Lives Matter Movement Can Teach the Health Care Industry",
      "summary": "A physician checks herself and her profession",
      "user": "JT Nakagawa",
      "section": "Elemental",
      "date": "9/11/2020",
      "time": "9",
      "popular": "No",
      "ranking": 693,
      "editorPick": "No",
      "mediumLink": "https://elemental.medium.com/5-lessons-the-black-lives-matter-movement-can-teach-the-health-care-industry-24d60fa7782f"
    },
    {
      "cover": "https://miro.medium.com/max/700/1*2J1YRGI9VhWVcUlAVXLImA.jpeg",
      "title": "A Supercomputer Analyzed Covid-19 — and an Interesting New Theory Has Emerged",
      "summary": "A closer look at the Bradykinin hypothesis",
      "user": "Thomas Smith",
      "section": "Popular",
      "date": "9/1/2020",
      "time": "8",
      "popular": "Si",
      "ranking": 46000,
      "editorPick": "No",
      "mediumLink": "https://elemental.medium.com/a-supercomputer-analyzed-covid-19-and-an-interesting-new-theory-has-emerged-31cb8eba9d63"
    },
    {
      "cover": "https://miro.medium.com/max/700/1*sXUdo_e1uWjzXa9cbS-DSQ.jpeg",
      "title": "33 Things I Stole From People Smarter Than Me",
      "summary": "Take them, adapt them, and apply them to your life",
      "user": "Ryan Holiday",
      "section": "Popular",
      "date": "6/17/2020",
      "time": "10",
      "popular": "Si",
      "ranking": 23000,
      "editorPick": "No",
      "mediumLink": "https://forge.medium.com/33-things-i-stole-from-people-smarter-than-me-on-the-way-to-33-c38e368e5cb8"
    },
    {
      "cover": "https://miro.medium.com/max/2400/1*JNQPEIjsuO7cf1Z4NXdBLA.jpeg",
      "title": "Your ‘Surge Capacity’ Is Depleted — It’s Why You Feel Awful",
      "summary": "Here’s how to pull yourself out of despair and live your life",
      "user": "Tara Haelle",
      "section": "Popular",
      "date": "8/17/2020",
      "time": "13",
      "popular": "Si",
      "ranking": 17000,
      "editorPick": "No",
      "mediumLink": "https://elemental.medium.com/your-surge-capacity-is-depleted-it-s-why-you-feel-awful-de285d542f4c"
    },
    {
      "cover": "https://miro.medium.com/max/1000/0*PPhiSVEK2gwcqPaN",
      "title": "Don’t Believe the Election Polls. Look at the Odds Instead.",
      "summary": "The most reliable poll for the next president of the United States",
      "user": "Everett Minshall",
      "section": "Popular",
      "date": "9/9/2020",
      "time": "5",
      "popular": "Si",
      "ranking": 8500,
      "editorPick": "No",
      "mediumLink": "https://medium.com/discourse/dont-believe-the-election-polls-look-at-the-odds-instead-3a52f3b36f1"
    },
    {
      "cover": "https://miro.medium.com/max/700/1*DI4vOuJO8jokc9QtElI8kA.jpeg",
      "title": "I Lost My Best Friend of Two Decades To Trump",
      "summary": "The heart is cruel above all things",
      "user": "Felicia C. Sullivan",
      "section": "Popular",
      "date": "9/4/2020",
      "time": "9",
      "popular": "Si",
      "ranking": 11250,
      "editorPick": "No",
      "mediumLink": "https://humanparts.medium.com/i-lost-my-best-friend-of-two-decades-to-trump-ec883b12bdea"
    },
    {
      "cover": "https://miro.medium.com/max/700/1*1nEfsoxOLlPjoq0h-meWtw.png",
      "title": "Clarifying the True Fatality Rate of Covid-19: Same as the Flu?",
      "summary": "The answer depends on which fatality rate jargon one uses. And there are better metrics to grasp the health toll of Covid-19.",
      "user": "Shin Jie Yong",
      "section": "Popular",
      "date": "9/8/2020",
      "time": "7",
      "popular": "Si",
      "ranking": 2900,
      "editorPick": "No",
      "mediumLink": "https://medium.com/microbial-instincts/clarifying-the-true-fatality-rate-of-covid-19-same-as-the-flu-8148e38b9ab5"
    },
    {
      "cover": "https://miro.medium.com/max/1000/1*xMhszwWuhxXvomadoirQ4w.jpeg",
      "title": "How One Covid-19 Doctor Became a Ventilator Whistleblower",
      "summary": "While caring for people with the disease, Dr. Cameron Kyle-Sidell began to suspect that the Covid-19 treatment consensus was wrong",
      "user": "Erik Ofgang",
      "section": "Popular",
      "date": "9/10/2020",
      "time": "12m",
      "popular": "Si",
      "ranking": 1100,
      "editorPick": "No",
      "mediumLink": "https://elemental.medium.com/how-one-covid-19-doctor-became-a-ventilator-whistleblower-a1c2dbdd1b06"
    },
    {
      "cover": "https://miro.medium.com/max/1000/1*WAFDoOPQIn1icAiuSBImHw.jpeg",
      "title": "Why Tesla’s Battery Day Will Actually Live Up to the Hype",
      "summary": "Elon Musk will likely announce his EVs have finally become as cheap as conventional cars",
      "user": "Steve LeVine",
      "section": "Popular",
      "date": "9/10/2020",
      "time": "9",
      "popular": "Si",
      "ranking": 3850,
      "editorPick": "No",
      "mediumLink": "https://marker.medium.com/why-teslas-battery-day-will-actually-live-up-to-the-hype-f10b4c74dc9b"
    },
    {
      "cover": "https://miro.medium.com/max/1000/1*taVN_55rDkr07EOuiUyRnQ.jpeg",
      "title": "Remote Work Is Killing the Hidden Trillion-Dollar Office Economy",
      "summary": "From airlines to Starbucks, a massive part of our economy hinges on white-collar workers returning to the office",
      "user": "Steve LeVine",
      "section": "Popular",
      "date": "9/1/2020",
      "time": "9",
      "popular": "Si",
      "ranking": 12300,
      "editorPick": "No",
      "mediumLink": "https://marker.medium.com/remote-work-is-killing-the-hidden-trillion-dollar-office-economy-5800af06b007"
    },
    {
      "cover": "https://miro.medium.com/max/1200/1*1Vb9u9nL_m5i5DEJUwptJw.gif",
      "title": "The Best Strength Training Workout Is Surprisingly Easy",
      "summary": "The number of reps and sets you do is less important than these fundamentals",
      "user": "Christie Aschwanden",
      "section": "Popular",
      "date": "9/2/2020",
      "time": "7",
      "popular": "Si",
      "ranking": 31200,
      "editorPick": "No",
      "mediumLink": "https://elemental.medium.com/the-best-strength-training-workout-is-surprisingly-easy-a7c7eb095a6f"
    },
    {
      "cover": "https://miro.medium.com/max/700/1*KqSyO0b0qJM5h_Wep6KE8w.jpeg",
      "title": "Nazi Hippies: When the New Age and Far Right Overlap",
      "summary": "Both the New Age and the far right are drawn to conspiracy theories",
      "user": "Jules Evans",
      "section": "Popular",
      "date": "9/4/2020",
      "time": "9",
      "popular": "Si",
      "ranking": 43100,
      "editorPick": "No",
      "mediumLink": "https://gen.medium.com/nazi-hippies-when-the-new-age-and-far-right-overlap-d1a6ddcd7be4"
    },
    {
      "cover": "https://miro.medium.com/max/700/1*nfel7Ucy5nsolMEfDfCx6g.jpeg",
      "title": "Leaked Salary Spreadsheet Reveals Microsoft Employee Earnings for a Second Year",
      "summary": "Sharing compensation data has become an annual tradition at Microsoft during this time of year",
      "user": "Dave Gershgorn",
      "section": "Popular",
      "date": "9/2/2020",
      "time": "4",
      "popular": "Si",
      "ranking": 16348,
      "editorPick": "No",
      "mediumLink": "https://onezero.medium.com/leaked-salary-spreadsheet-reveals-microsoft-employee-earnings-for-a-second-year-d1466132d309"
    },
    {
      "cover": "https://miro.medium.com/max/700/1*rgiSLUMbpgIF8yZr2YqyqA.jpeg",
      "title": "What I Found Out When I Blocked Apps from Tracking My iPhone for One Week",
      "summary": "What happens on your iPhone doesn’t stay on your iPhone after all",
      "user": "Rob Sturgeon",
      "section": "Popular",
      "date": "8/25/2020",
      "time": "13",
      "popular": "Si",
      "ranking": 24982,
      "editorPick": "No",
      "mediumLink": "https://medium.com/storiusmag/what-i-found-out-when-i-blocked-apps-from-tracking-my-iphone-for-1-week-f1df165d1f8a"
    },
    {
      "cover": "https://miro.medium.com/max/700/1*rBvGWo4ZXnbgzznL9k9aXw.jpeg",
      "title": "VW One-Ups Tesla With a Revolutionary Battery Breakthrough",
      "summary": "After 10 years in stealth mode, QuantumScape launches an IPO, becoming the first U.S. battery company to go public in a decade",
      "user": "Steve LeVine",
      "section": "Popular",
      "date": "9/3/2020",
      "time": "5",
      "popular": "Si",
      "ranking": 17403,
      "editorPick": "No",
      "mediumLink": "https://marker.medium.com/vw-one-ups-tesla-with-a-revolutionary-battery-breakthrough-be51849ea092"
    },
    {
      "cover": "https://miro.medium.com/max/1620/1*4mlptijhTvoVp7jleBqOLg.jpeg",
      "title": "We Don’t Know How to Warn You Any Harder. America is Dying.",
      "summary": "We Survivors of Authoritarianism Have a Message America Needs to Hear: This is Exactly How it Happens, and It’s Happening Here.",
      "user": "umair haque",
      "section": "Popular",
      "date": "8/29/2020",
      "time": "11",
      "popular": "Si",
      "ranking": 43650,
      "editorPick": "No",
      "mediumLink": "https://eand.co/we-dont-know-how-to-warn-you-any-harder-america-is-dying-26ff80912391"
    },
    {
      "cover": "https://miro.medium.com/max/700/0*i8k1hJRm2B7QCk7V",
      "title": "Do People With Glasses Have a Covid-19 Edge?",
      "summary": "What we know about eye barriers and the virus",
      "user": "Alexandra Sifferlin",
      "section": "Coronavirus",
      "date": "09/16/2020",
      "time": "3",
      "popular": "No",
      "ranking": 82,
      "editorPick": "No",
      "mediumLink": "https://coronavirus.medium.com/do-people-with-glasses-have-a-covid-19-edge-745c9fbaf3b"
    },
    {
      "cover": "https://miro.medium.com/max/700/0*56T0YEGcJ7YChHVJ",
      "title": "What New Data Reveals About Kids and Coronavirus Spread",
      "summary": "New research shows kids can spread Covid-19 to family members, even when they are asymptomatic",
      "user": "Yasmin Tayag",
      "section": "Coronavirus",
      "date": "9/15/2020",
      "time": "4",
      "popular": "No",
      "ranking": 34,
      "editorPick": "No",
      "mediumLink": "https://coronavirus.medium.com/what-new-data-reveals-about-kids-and-coronavirus-transmission-198f9c24226"
    },
    {
      "cover": "https://miro.medium.com/max/700/0*wWDNEH02dUFrz1LL",
      "title": "College and Coronavirus Are Not a Great Mix",
      "summary": "So what can be done?",
      "user": "Coronavirus Blog Team",
      "section": "Coronavirus",
      "date": "9/15/2020",
      "time": "3",
      "popular": "No",
      "ranking": 128,
      "editorPick": "No",
      "mediumLink": "https://coronavirus.medium.com/college-and-coronavirus-are-not-a-great-mix-f06dcd6ffef8"
    },
    {
      "cover": "https://miro.medium.com/max/700/1*9OBbtph6pMVYVs2gTjTcEw.jpeg",
      "title": "Scientists Plotting Sedition? Michael Caputo’s Perfect Conspiracy Theory",
      "summary": "The Trump loyalist sows fear and hatred by pulling all the classic levers of conspiracism",
      "user": "Robert Roy Britt",
      "section": "Coronavirus",
      "date": "9/15/2020",
      "time": "4",
      "popular": "No",
      "ranking": 66,
      "editorPick": "No",
      "mediumLink": "https://coronavirus.medium.com/scientists-plotting-sedition-michael-caputos-perfect-conspiracy-theory-f37e69577d7a"
    },
    {
      "cover": "https://miro.medium.com/max/700/1*6vf3ROddhUhOSVpeFImGjA.jpeg",
      "title": "Our Treatment of the Elderly in the Pandemic Is Morally Bankrupt",
      "summary": "In societies where elders are honored around the world, the death toll is much lower",
      "user": "Andy Slavitt",
      "section": "Coronavirus",
      "date": "9/14/2020",
      "time": "4",
      "popular": "No",
      "ranking": 476,
      "editorPick": "No",
      "mediumLink": "https://coronavirus.medium.com/our-treatment-of-the-elderly-in-the-pandemic-is-morally-bankrupt-9ed78a4a42c3"
    },
    {
      "cover": "https://miro.medium.com/max/700/1*b44FaDnWICb5sVCTqdWDhQ.jpeg",
      "title": "Trust in Fauci and the CDC Falls as Partisan Gap Widens",
      "summary": "Fear, misinformation and the widening political divide over science and expertise threaten our democracy, experts say",
      "user": "Robert Roy Britt",
      "section": "Coronavirus",
      "date": "9/11/2020",
      "time": "5",
      "popular": "No",
      "ranking": 217,
      "editorPick": "No",
      "mediumLink": "https://coronavirus.medium.com/trust-in-fauci-and-the-cdc-falls-as-partisan-gap-widens-ec2c8ae92a72"
    },
    {
      "cover": "https://miro.medium.com/max/700/1*wVWCCppuAQsWqYNGEIA_Aw.jpeg",
      "title": "The Latest on Covid-19 Vaccines",
      "summary": "Everything that happened in the race to find a coronavirus vaccine this week",
      "user": "Yasmin Tayag",
      "section": "Coronavirus",
      "date": "9/11/2020",
      "time": "2",
      "popular": "No",
      "ranking": 222,
      "editorPick": "No",
      "mediumLink": "https://coronavirus.medium.com/the-latest-on-covid-19-vaccines-d7db71ba99cf"
    },
    {
      "cover": "https://miro.medium.com/max/700/1*nzst9WJ8ak0I-vnaed8yJw.jpeg",
      "title": "Keep People Calm!?",
      "summary": "While President Trump was downplaying Covid-19 to avoid ‘panic’ among Americans, he was also doing nothing to protect them",
      "user": "Andy Slavitt",
      "section": "Coronavirus",
      "date": "9/11/2020",
      "time": "3",
      "popular": "No",
      "ranking": 591,
      "editorPick": "No",
      "mediumLink": "https://coronavirus.medium.com/keep-people-calm-9cd1e2d0c9bc"
    },
    {
      "cover": "https://miro.medium.com/max/700/1*avIiaBhsIFFSD_QvjiLq5w.jpeg",
      "title": "What’s Life Worth? The Dollar Cost of 200,000 Dead Americans",
      "summary": "Life is precious, but not priceless, economists say. So what’s the value of each life lost to Covid-19?",
      "user": "Robert Roy Britt",
      "section": "Coronavirus",
      "date": "9/11/2020",
      "time": "4",
      "popular": "No",
      "ranking": 255,
      "editorPick": "No",
      "mediumLink": "https://coronavirus.medium.com/whats-life-worth-the-dollar-cost-of-200-000-dead-americans-44b9d6a4791f"
    },
    {
      "cover": "https://miro.medium.com/max/700/1*T4aLtTn_M12eXIb0e5fprg.jpeg",
      "title": "The Problem With DIY Covid-19 Vaccines",
      "summary": "",
      "user": "Alexandra Sifferlin",
      "section": "Coronavirus",
      "date": "9/11/2020",
      "time": "2",
      "popular": "No",
      "ranking": 163,
      "editorPick": "No",
      "mediumLink": "https://coronavirus.medium.com/the-problem-with-diy-covid-19-vaccines-5d47f7fc43a1"
    },
    {
      "cover": "https://miro.medium.com/max/700/1*weU1FamrUWjqlOa77rovNA.jpeg",
      "title": "What Else Does He Know?",
      "summary": "The pandemic would have been different under anyone but a madman",
      "user": "Andy Slavitt",
      "section": "Coronavirus",
      "date": "9/11/2020",
      "time": "3",
      "popular": "No",
      "ranking": 2100,
      "editorPick": "No",
      "mediumLink": "https://coronavirus.medium.com/what-else-does-he-know-994fbd9edb1e"
    },
    {
      "cover": "https://miro.medium.com/max/700/1*fxjl17QH6Y27Ra7AcDP6tQ.jpeg",
      "title": "The Long History of Redlining Makes Covid-19 Worse for Black Americans",
      "summary": "Health effects of racist housing policy persist 80 years later",
      "user": "Yasmin Tayag",
      "section": "Coronavirus",
      "date": "9/11/2020",
      "time": "2",
      "popular": "No",
      "ranking": 299,
      "editorPick": "No",
      "mediumLink": "https://coronavirus.medium.com/the-long-history-of-redlining-makes-covid-19-worse-for-black-americans-efd520f8221c"
    },
    {
      "cover": "https://miro.medium.com/max/700/0*ypJoO3FrWRN8W_EI",
      "title": "This Bug Is Beatable",
      "summary": "Social distancing is a privilege. We forget because it feels like a hassle.",
      "user": "Andy Slavitt",
      "section": "Coronavirus",
      "date": "9/8/2020",
      "time": "4",
      "popular": "No",
      "ranking": 1200,
      "editorPick": "No",
      "mediumLink": "https://coronavirus.medium.com/this-bug-is-beatable-bb495cfef766"
    },
    {
      "cover": "https://miro.medium.com/max/700/0*CLCUARGnlOsFIAEl",
      "title": "Enough With the Herd Immunity Mansplaining",
      "summary": "What people who throw around ‘herd immunity’ often don’t understand is ‘herd’ or ‘immunity’",
      "user": "Andy Slavitt",
      "section": "Coronavirus",
      "date": "8/9/2020",
      "time": "4",
      "popular": "No",
      "ranking": 1300,
      "editorPick": "No",
      "mediumLink": "https://coronavirus.medium.com/enough-with-the-herd-immunity-mansplaining-6f1e60ade2ff"
    },
    {
      "cover": "https://miro.medium.com/max/700/1*BShEpr6CflEGP6u3GcG3bw.jpeg",
      "title": "Writing About Politics Sucks",
      "summary": "This is Drew’s swan song for his GEN column. Not really a song. More of a dirge.",
      "user": "Drew Magary",
      "section": "Gen",
      "date": "09/16/2020",
      "time": "5",
      "popular": "No",
      "ranking": 1800,
      "editorPick": "No",
      "mediumLink": "https://gen.medium.com/writing-about-politics-sucks-cb9a001eef8e"
    },
    {
      "cover": "https://miro.medium.com/max/700/1*FO356AR580V3W_7LUBVZRA.jpeg",
      "title": "Open Thread: Have You Lost a Loved One to a Conspiracy Theory?",
      "summary": "The past four years have transformed fringe theories into mainstream movements. How has it changed us?",
      "user": "GEN Editors",
      "section": "Gen",
      "date": "9/17/2020",
      "time": "2",
      "popular": "No",
      "ranking": 36,
      "editorPick": "No",
      "mediumLink": "https://gen.medium.com/open-thread-have-you-lost-a-loved-one-to-a-conspiracy-theory-e027da670501"
    },
    {
      "cover": "https://miro.medium.com/max/1000/1*vg0BgGS8xG6ABu51sQeFLA.jpeg",
      "title": "The President Ruined a Business I Spent 14 Years Building",
      "summary": "Kate Goldwater says she’s shuttering her vintage thrift shop because of the government’s poorly handled pandemic response",
      "user": "Meredith Clark",
      "section": "Gen",
      "date": "9/17/2020",
      "time": "5",
      "popular": "No",
      "ranking": 526,
      "editorPick": "No",
      "mediumLink": "https://gen.medium.com/the-president-ruined-a-business-i-spent-14-years-building-7ed367524e26"
    },
    {
      "cover": "https://miro.medium.com/max/700/1*9UXdK4TONweWFj5Va0louw.jpeg",
      "title": "America Is Letting Paranoia Win",
      "summary": "The spread of QAnon and other conspiracy theories shows how easily people turn to superstition and panic when the world falls apart",
      "user": "Sady Doyle",
      "section": "Gen",
      "date": "9/17/2020",
      "time": "6",
      "popular": "No",
      "ranking": 401,
      "editorPick": "No",
      "mediumLink": "https://gen.medium.com/america-is-letting-paranoia-win-134630af6acc"
    },
    {
      "cover": "https://miro.medium.com/max/700/1*HRJISVNE4MH0bF30vxzHVA.jpeg",
      "title": "Country Music Was the Soundtrack of My Hmong Upbringing",
      "summary": "For a refugee family in St. Paul, Billy Ray Cyrus and Tanya Tucker provided a window to a different, more Americanized world",
      "user": "Kao Kalia Yang",
      "section": "Gen",
      "date": "9/16/2020",
      "time": "6",
      "popular": "No",
      "ranking": 514,
      "editorPick": "No",
      "mediumLink": "https://gen.medium.com/country-music-was-the-soundtrack-of-my-hmong-upbringing-960a9a694fb"
    },
    {
      "cover": "https://miro.medium.com/max/1000/1*BKShvusS5zjOnnvN7vLDkA.jpeg",
      "title": "The GOP Stole Satire From the Left",
      "summary": "Trump has brought pranksterism to the Republican Party. That used to be liberals’ specialty.",
      "user": "Douglas Rushkoff",
      "section": "Gen",
      "date": "9/16/2020",
      "time": "8",
      "popular": "No",
      "ranking": 1200,
      "editorPick": "No",
      "mediumLink": "https://gen.medium.com/the-gop-stole-satire-from-the-left-6f373b8e5bad"
    },
    {
      "cover": "https://miro.medium.com/max/700/1*DxR_AmSUk87UrEesz72fnQ.jpeg",
      "title": "This Week in Trumpland Corruption: Oracle Predicts a Payday",
      "summary": "Trump donor Larry Ellison lands a big win with his company’s TikTok contract, and the president seeks the DOJ’s help in his case against E. Jean Carroll",
      "user": "Max Ufberg",
      "section": "Gen",
      "date": "9/16/2020",
      "time": "4",
      "popular": "No",
      "ranking": 491,
      "editorPick": "No",
      "mediumLink": "https://gen.medium.com/this-week-in-trumpland-corruption-oracle-predicts-a-payday-44cdc3aabdc8"
    },
    {
      "cover": "https://miro.medium.com/max/700/1*Bn-rNz1IOFUdB_Qv_lKDLw.jpeg",
      "title": "People Need to Give Up the Illusion of Bipartisan Friendship",
      "summary": "If someone doesn’t want to be your friend because of your political beliefs, you should take it as a sign that you are wrong — not wronged",
      "user": "Jessica Valenti",
      "section": "Gen",
      "date": "9/16/2020",
      "time": "4",
      "popular": "No",
      "ranking": 2200,
      "editorPick": "No",
      "mediumLink": "https://gen.medium.com/people-need-to-give-up-the-illusion-of-bipartisan-friendship-2f1b1838caae"
    },
    {
      "cover": "https://miro.medium.com/max/2160/1*VY1ahdg9nYq6FILxeiemsQ.jpeg",
      "title": "Inside Kelly Brogan’s Covid-Denying, Vax-Resistant Conspiracy Machine",
      "summary": "Alt-health meets alt-right in the ‘conspirituality’ movement",
      "user": "Matthew Remski",
      "section": "Gen",
      "date": "9/16/2020",
      "time": "23",
      "popular": "No",
      "ranking": 795,
      "editorPick": "No",
      "mediumLink": "https://gen.medium.com/inside-kelly-brogans-covid-denying-vax-resistant-conspiracy-machine-28342e6369b1"
    },
    {
      "cover": "https://miro.medium.com/max/700/1*rUu-Bgcd3nXT_nT5TahTCg.jpeg",
      "title": "Trump Is a Lost Cause. We Have to Change Ourselves.",
      "summary": "The president is a reflection of our worst instincts",
      "user": "Tony Schwartz",
      "section": "Gen",
      "date": "9/15/2020",
      "time": "6",
      "popular": "No",
      "ranking": 3100,
      "editorPick": "No",
      "mediumLink": "https://gen.medium.com/trump-is-a-lost-cause-we-have-to-change-ourselves-dd3d412e3aa8"
    },
    {
      "cover": "https://miro.medium.com/max/700/1*DEqAWGfHy2-NQi-EIM0Gdw.jpeg",
      "title": "These Frontline Workers Are Protecting Protestors at All Costs",
      "summary": "For volunteer medics and legal observers, confronting police violence can come with mental and physical tolls",
      "user": "Iman Sultan",
      "section": "Gen",
      "date": "9/15/2020",
      "time": "6",
      "popular": "No",
      "ranking": 372,
      "editorPick": "No",
      "mediumLink": "https://gen.medium.com/frontline-workers-are-putting-it-all-on-the-line-828fcc2025b5"
    },
    {
      "cover": "https://miro.medium.com/max/700/1*fF1O2mwdOjnjtQF1DTvBrA.jpeg",
      "title": "Vigilantes Are Longtime Defenders of White Supremacy",
      "summary": "Trump’s warnings of a violent left are hand-me-downs from his vigilante predecessors",
      "user": "Jared Keller",
      "section": "Gen",
      "date": "9/15/2020",
      "time": "7",
      "popular": "No",
      "ranking": 547,
      "editorPick": "No",
      "mediumLink": "https://gen.medium.com/vigilantes-are-longtime-defenders-of-white-supremacy-2f0c17ac1011"
    },
    {
      "cover": "https://miro.medium.com/max/700/1*JhCLuh7MrwWglayuTDzsVQ.jpeg",
      "title": "Americans Have Collective Amnesia Around Polling",
      "summary": "‘Polls are not prophesies’ and other things we refuse to learn",
      "user": "Max Ufberg",
      "section": "Gen",
      "date": "9/14/2020",
      "time": "6",
      "popular": "No",
      "ranking": 193,
      "editorPick": "No",
      "mediumLink": "https://gen.medium.com/americans-have-collective-amnesia-around-polling-57c1dfa46761"
    },
    {
      "cover": "https://miro.medium.com/max/700/1*RDWV8flPukDuEh4qOk2Qbg.jpeg",
      "title": "Drinking in Pods, ‘Social Snitching,’ and More Covid Freshman Experiences",
      "summary": "How do you make friends in your first weeks at college when you don’t know who you can trust?",
      "user": "Rainesford Stauffer",
      "section": "Gen",
      "date": "9/14/2020",
      "time": "8",
      "popular": "No",
      "ranking": 338,
      "editorPick": "No",
      "mediumLink": "https://gen.medium.com/drinking-in-pods-social-snitching-and-more-covid-freshman-experiences-a4eb24be11"
    },
    {
      "cover": "https://miro.medium.com/max/700/1*ZDCc8nDwCOhJ_9nq3BXg7g.jpeg",
      "title": "White People Are Crowding the Conversation Around Race",
      "summary": "There’s a fine line between being an ally and making a movement all about yourself",
      "user": "Jessica Valenti",
      "section": "Gen",
      "date": "9/11/2020",
      "time": "4",
      "popular": "No",
      "ranking": 2200,
      "editorPick": "No",
      "mediumLink": "https://gen.medium.com/white-people-are-crowding-the-conversation-around-race-31e9ae37a27a"
    },
    {
      "cover": "https://miro.medium.com/max/700/1*nv1XTuJY6ZU6OCKGHKryYg.jpeg",
      "title": "What Peter Norman Taught Me About Genuine Solidarity",
      "summary": "Be true in everything you do, especially your activism",
      "user": "Saffana",
      "section": "Momentum",
      "date": "9/10/2020",
      "time": "3",
      "popular": "No",
      "ranking": 622,
      "editorPick": "No",
      "mediumLink": "https://momentum.medium.com/what-peter-norman-taught-me-about-genuine-solidarity-dc4ea8608f4e"
    },
    {
      "cover": "https://miro.medium.com/max/700/1*NcQmacnHYbSc7ZkB-kGfIA.jpeg",
      "title": "Naomi Osaka’s Face Masks Speak 1,000 Words",
      "summary": "The tennis star honors police brutality victims at the U.S. Open",
      "user": "Jada Gomez",
      "section": "Momentum",
      "date": "9/9/2020",
      "time": "2",
      "popular": "No",
      "ranking": 125,
      "editorPick": "No",
      "mediumLink": "https://momentum.medium.com/naomi-osakas-face-masks-speak-1-000-words-a932653bd3f5"
    },
    {
      "cover": "https://miro.medium.com/max/700/1*TZ4KBLn42vTARAmDzjlgeA.jpeg",
      "title": "There Is No ‘After’ the Protests",
      "summary": "A new series from GEN looks at how we can reconcile our organizing lives with our working lives",
      "user": "Hanif Abdurraqib",
      "section": "Momentum",
      "date": "9/8/2020",
      "time": "4",
      "popular": "No",
      "ranking": 242,
      "editorPick": "No",
      "mediumLink": "https://momentum.medium.com/there-is-no-after-the-protests-caaad3b1cabf"
    },
    {
      "cover": "https://miro.medium.com/max/700/1*-JlMqTDshGxW3xscsv8BvA.jpeg",
      "title": "Bearing Witness Even in Death",
      "summary": "",
      "user": "Adrienne Samuels Gibbs",
      "section": "Momentum",
      "date": "9/4/2020",
      "time": "2",
      "popular": "No",
      "ranking": 965,
      "editorPick": "No",
      "mediumLink": "https://momentum.medium.com/bearing-witness-even-in-death-edc7fd5cac73"
    },
    {
      "cover": "https://miro.medium.com/max/700/1*ecYD25LDUnm_f1rr7mxVHg.jpeg",
      "title": "2 Police Confrontations, 2 Very Different Outcomes",
      "summary": "",
      "user": "Indrani Sen",
      "section": "Momentum",
      "date": "9/3/2020",
      "time": "2",
      "popular": "No",
      "ranking": 33,
      "editorPick": "No",
      "mediumLink": "https://momentum.medium.com/2-police-confrontations-2-very-different-outcomes-3a41d7485d8d"
    },
    {
      "cover": "https://miro.medium.com/max/700/1*bTizslFcU67cMavoy__atw.jpeg",
      "title": "Passive Voice Is Dangerous. These Examples Show Why.",
      "summary": "It’s time to stop trying so hard to say nothing at all",
      "user": "Adrienne Samuels Gibbs",
      "section": "Momentum",
      "date": "9/3/2020",
      "time": "4",
      "popular": "No",
      "ranking": 1800,
      "editorPick": "No",
      "mediumLink": "https://momentum.medium.com/check-your-privilege-and-your-passive-voice-6b301a9bcccc"
    },
    {
      "cover": "https://miro.medium.com/max/3500/1*poouygomQCNfWnzT2TrQsA.jpeg",
      "title": "Biking While Black Shouldn’t Be a Death Sentence",
      "summary": "",
      "user": "Stephanie Georgopulos",
      "section": "Momentum",
      "date": "9/3/2020",
      "time": "3",
      "popular": "No",
      "ranking": 409,
      "editorPick": "No",
      "mediumLink": "https://momentum.medium.com/biking-while-black-shouldnt-be-a-death-sentence-45d3d8c0f52f"
    },
    {
      "cover": "https://miro.medium.com/max/700/1*MxqgDBezZ2k9PDcBDhOQdQ.jpeg",
      "title": "John Boyega Will No Longer ‘Protest Quietly’",
      "summary": "The actor and activist doesn’t mince words when it comes to his treatment as a pivotal Black character in the ‘Star Wars’ franchise",
      "user": "Jada Gomez",
      "section": "Momentum",
      "date": "9/2/2020",
      "time": "2",
      "popular": "No",
      "ranking": 86,
      "editorPick": "No",
      "mediumLink": "https://momentum.medium.com/john-boyega-will-no-longer-protest-quietly-80855052d09c"
    },
    {
      "cover": "https://miro.medium.com/max/700/1*Sk6X7uU3bP2diUuKAA8TNA.png",
      "title": "The Price of Keeping Our Heads Down",
      "summary": "",
      "user": "Indrani Sen",
      "section": "Momentum",
      "date": "9/2/2020",
      "time": "2",
      "popular": "No",
      "ranking": 206,
      "editorPick": "No",
      "mediumLink": "https://momentum.medium.com/the-price-of-keeping-our-heads-down-7164e90740bc"
    },
    {
      "cover": "https://miro.medium.com/max/700/1*IBIonSMZKjTE8wyC9PHZ3g.jpeg",
      "title": "Black Joy Matters, Too",
      "summary": "Joy gives us energy to keep fighting another day",
      "user": "Jolie A. Doggett",
      "section": "Momentum",
      "date": "9/1/2020",
      "time": "3",
      "popular": "No",
      "ranking": 373,
      "editorPick": "No",
      "mediumLink": "https://momentum.medium.com/black-joy-matters-too-1d764b9c211f"
    },
    {
      "cover": "https://miro.medium.com/max/700/1*dolwyh-8eoZYYJM0ZSkCAQ.jpeg",
      "title": "A Confederate Statue Stands in Chadwick Boseman’s Hometown. 13,000 Fans Want a Boseman Memorial There Instead.",
      "summary": "",
      "user": "Dave Gershgorn",
      "section": "Momentum",
      "date": "9/1/2020",
      "time": "2",
      "popular": "No",
      "ranking": 143,
      "editorPick": "No",
      "mediumLink": "https://momentum.medium.com/a-confederate-statue-stands-in-chadwick-bosemans-hometown-26fb87bf08d3"
    },
    {
      "cover": "https://miro.medium.com/max/700/1*2OJ2gugcpe2KPUdtSjH_-g.jpeg",
      "title": "A New Strike for Racial Justice Among Athletes Starts With the Milwaukee Bucks’ Historic Move",
      "summary": "The NBA, WNBA, MLB, and the U.S. Tennis Association are lockstep in protest",
      "user": "Jada Gomez",
      "section": "Momentum",
      "date": "8/27/2020",
      "time": "2",
      "popular": "No",
      "ranking": 423,
      "editorPick": "No",
      "mediumLink": "https://momentum.medium.com/a-new-strike-for-racial-justice-among-athletes-start-with-the-milwaukee-bucks-historic-move-ed6e26089edb"
    },
    {
      "cover": "https://miro.medium.com/max/700/1*B5PuV-xXDB9h5wS43RTRYA.jpeg",
      "title": "Your Brain, Stressed Out — But in a Good Way!",
      "summary": "",
      "user": "Dana G Smith",
      "section": "Elemental",
      "date": "9/17/2020",
      "time": "2",
      "popular": "No",
      "ranking": 69,
      "editorPick": "No",
      "mediumLink": "https://elemental.medium.com/your-brain-stressed-out-but-in-a-good-way-43c0df1c8a14"
    },
    {
      "cover": "https://miro.medium.com/max/700/1*84KfskBhVNof9d4657nfbg.jpeg",
      "title": "Can You Measure Well-Being?",
      "summary": "An inside look from scientists working to quantify feelings",
      "user": "Liz Redford",
      "section": "Elemental",
      "date": "9/17/2020",
      "time": "7",
      "popular": "No",
      "ranking": 147,
      "editorPick": "No",
      "mediumLink": "https://elemental.medium.com/can-you-measure-well-being-3875e79d108a"
    },
    {
      "cover": "https://miro.medium.com/max/1500/1*7-MtQSncJRs875qBH0oXCg.png",
      "title": "It’s Okay to Have Questions About a Covid-19 Vaccine. Here’s What to Ask.",
      "summary": "The approval process, interpreting clinical trial results, and how to be confident in your choice to get the vaccine",
      "user": "Tara Haelle",
      "section": "Elemental",
      "date": "9/16/2020",
      "time": "10",
      "popular": "No",
      "ranking": 613,
      "editorPick": "No",
      "mediumLink": "https://elemental.medium.com/its-okay-to-have-questions-about-a-covid-19-vaccine-here-s-what-to-ask-e8196cb8f222"
    },
    {
      "cover": "https://miro.medium.com/max/2000/1*TAb2ortktRLcBNOSTyn5Vg.jpeg",
      "title": "‘Biofeedback’ Could Ease Headaches, Anxiety — and Maybe a Lot Else",
      "summary": "By providing a window onto the body’s inner workings, biofeedback could help people control what was once thought to be ungovernable",
      "user": "Markham Heid",
      "section": "Elemental",
      "date": "9/16/2020",
      "time": "6",
      "popular": "No",
      "ranking": 311,
      "editorPick": "No",
      "mediumLink": "https://elemental.medium.com/biofeedback-could-ease-headaches-anxiety-and-maybe-a-lot-else-630f3c51f99f"
    },
    {
      "cover": "https://miro.medium.com/max/2000/1*cjhRKlaZ2vVx_9Ym-U0l4Q.jpeg",
      "title": "Music Can Get Us Through This",
      "summary": "Why a good tune is so good at relieving stress, anxiety, sadness, and other negative emotional states",
      "user": "Markham Heid",
      "section": "Elemental",
      "date": "9/10/2020",
      "time": "6",
      "popular": "No",
      "ranking": 1000,
      "editorPick": "No",
      "mediumLink": "https://elemental.medium.com/music-can-get-us-through-this-7af0041a607"
    },
    {
      "cover": "https://miro.medium.com/max/700/1*RKi-B-MkEEna6fvRfwVYlg.jpeg",
      "title": "All This 2020 Tumult Could Make Your Brain Sharper",
      "summary": "This year has knocked our brains off of their hamster wheels, says neuroscientist David Eagleman",
      "user": "Darryn King",
      "section": "Elemental",
      "date": "9/9/2020",
      "time": "6",
      "popular": "No",
      "ranking": 679,
      "editorPick": "No",
      "mediumLink": "https://elemental.medium.com/all-this-2020-tumult-may-be-good-for-our-brains-d8b89ef34a8c"
    },
    {
      "cover": "https://miro.medium.com/max/700/1*STVdAGhOg8qNb2b8OPwizg.jpeg",
      "title": "The Cities Where Gentrification and Covid-19 Collide",
      "summary": "A look at the crises impacting people of color in Miami, Oakland, and Brooklyn, where residents fight to protect their communities",
      "user": "Kovie Biakolo",
      "section": "Zora",
      "date": "9/16/2020",
      "time": "13",
      "popular": "No",
      "ranking": 210,
      "editorPick": "No",
      "mediumLink": "https://zora.medium.com/the-cities-where-gentrification-and-covid-19-collide-f672f44f0a9b"
    },
    {
      "cover": "https://miro.medium.com/max/700/1*NtxDx21erxNBPZRVtjJKBg.jpeg",
      "title": "Own Your Worth, and Fight for It",
      "summary": "“I work very hard and I’m worth every cent.” — Naomi Campbell, supermodel",
      "user": "Morgan Jerkins",
      "section": "Zora",
      "date": "9/16/2020",
      "time": "2",
      "popular": "No",
      "ranking": 26,
      "editorPick": "No",
      "mediumLink": "https://zora.medium.com/own-your-worth-and-fight-for-it-d482038ebaef"
    },
    {
      "cover": "https://miro.medium.com/max/700/1*Qy5Fq5kfL7rYcUPBvM-WmQ.jpeg",
      "title": "Save Your Breath on Fools",
      "summary": "“Life’s too short to spend time trying to explain the obvious to an idiot.” — Gloria Naylor, author",
      "user": "Morgan Jerkins",
      "section": "Zora",
      "date": "9/16/2020",
      "time": "1",
      "popular": "No",
      "ranking": 290,
      "editorPick": "No",
      "mediumLink": "https://zora.medium.com/save-your-breath-on-fools-5a7a2f4162d1"
    },
    {
      "cover": "https://miro.medium.com/max/700/1*Q9ZJF9a1R9VUB91szoQeug.jpeg",
      "title": "Reparenting Through Play Is My New Form of Self-Care",
      "summary": "From hula hoops to jump ropes, it’s time to make a playdate for yourself",
      "user": "afrobella",
      "section": "Zora",
      "date": "9/16/2020",
      "time": "6",
      "popular": "No",
      "ranking": 151,
      "editorPick": "No",
      "mediumLink": "https://zora.medium.com/reparenting-through-play-is-my-new-form-of-self-care-831bc70f5b47"
    },
    {
      "cover": "https://miro.medium.com/max/700/1*heBfgmtJ5Y2tHyBES8sxMA.jpeg",
      "title": "As an Indo African Caribbean Woman, I See Myself in Kamala Harris",
      "summary": "She offers an opportunity for me to share my family’s island ancestry",
      "user": "Nadine Drummond",
      "section": "Zora",
      "date": "9/16/2020",
      "time": "7",
      "popular": "No",
      "ranking": 302,
      "editorPick": "No",
      "mediumLink": "https://zora.medium.com/as-an-indo-african-caribbean-woman-i-see-myself-in-kamala-harris-7539370cfbe9"
    },
    {
      "cover": "https://miro.medium.com/max/700/1*ni6B7aSks6IkSmUvJK58Tw.jpeg",
      "title": "The ‘Latinx’ Label Centers European Heritage. We Should Stop Using It.",
      "summary": "Let’s rethink an identity built on destruction, conquest, and the plundering of the Spanish empire",
      "user": "Adriana Maestas",
      "section": "Zora",
      "date": "9/15/2020",
      "time": "5",
      "popular": "No",
      "ranking": 834,
      "editorPick": "No",
      "mediumLink": "https://zora.medium.com/the-latinx-label-centers-european-heritage-we-should-stop-using-it-f3c9c0c813c3"
    },
    {
      "cover": "https://miro.medium.com/max/700/1*l8ozwcUiRXa93elYW0-usQ.jpeg",
      "title": "Forgive Yourself as an Act of Self-Love",
      "summary": "“If you haven’t forgiven yourself something, how can you forgive others?” — Dolores Huerta, labor rights activist",
      "user": "Morgan Jerkins",
      "section": "Zora",
      "date": "9/15/2020",
      "time": "1",
      "popular": "No",
      "ranking": 158,
      "editorPick": "No",
      "mediumLink": "https://zora.medium.com/forgive-yourself-as-an-act-of-self-love-29d946ac9639"
    },
    {
      "cover": "https://miro.medium.com/max/1000/1*dN921YnelujjYoElg3EoLQ.png",
      "title": "Mars Retrograde Plus a New Moon Are Tools: Use Them Wisely",
      "summary": "The astrology of September 14 — September 20, 2020",
      "user": "Ashleigh D. Jay",
      "section": "Zora",
      "date": "9/14/2020",
      "time": "10",
      "popular": "No",
      "ranking": 504,
      "editorPick": "No",
      "mediumLink": "https://zora.medium.com/mars-retrograde-plus-a-new-moon-are-tools-use-them-wisely-49241891047c"
    },
    {
      "cover": "https://miro.medium.com/max/700/1*uu8yIKW_rWJM5s_HSxpuyA.jpeg",
      "title": "Asexuality Is Not Just for White People, Says a New Book",
      "summary": "Angela Chen’s ‘Ace’ is a new and fresh addition to literature",
      "user": "Deena ElGenaidi",
      "section": "Zora",
      "date": "9/14/2020",
      "time": "5",
      "popular": "No",
      "ranking": 77,
      "editorPick": "No",
      "mediumLink": "https://zora.medium.com/this-journalist-is-on-a-mission-to-teach-the-world-about-asexuality-51404f5cbcc0"
    },
    {
      "cover": "https://miro.medium.com/max/700/1*V61FCWMd_7EzLplh_hM0jQ.jpeg",
      "title": "Cherish the Journey",
      "summary": "“What is often called exceptional ability is nothing more than persistent endeavor.” — Pauli Murray, lawyer, Episcopal priest, author, civil rights activist",
      "user": "Morgan Jerkins",
      "section": "Zora",
      "date": "9/14/2020",
      "time": "1",
      "popular": "No",
      "ranking": 109,
      "editorPick": "No",
      "mediumLink": "https://zora.medium.com/cherish-the-journey-e8ecf6806b4a"
    },
    {
      "cover": "https://miro.medium.com/max/700/1*SMNcttEaj2GKC-_-b22g5g.jpeg",
      "title": "A Decade-by-Decade Spin Through the Careers of Gladys Knight and Patti LaBelle",
      "summary": "Two lifetimes of Number 1 hits, TV shows, chicken, waffles, and pies led us to this historic soulstress song battle",
      "user": "Ayana Contreras",
      "section": "Zora",
      "date": "9/12/2020",
      "time": "6",
      "popular": "No",
      "ranking": 215,
      "editorPick": "No",
      "mediumLink": "https://zora.medium.com/a-decade-by-decade-spin-through-the-careers-of-gladys-knight-and-patti-labelle-c0e46fb74a4"
    },
    {
      "cover": "https://miro.medium.com/max/700/0*buhRKFlh9qN1updU",
      "title": "5 Iconic TV Friendships We Will Always Love",
      "summary": "From ‘A Different World’ to ‘I May Destroy You,’ we share the on-screen bonds that show the beauty of how our chosen family shapes and holds us",
      "user": "ZORA Editors",
      "section": "Zora",
      "date": "9/11/2020",
      "time": "2",
      "popular": "No",
      "ranking": 85,
      "editorPick": "No",
      "mediumLink": "https://zora.medium.com/5-iconic-tv-friendships-we-will-always-love-9eaeb45effa9"
    },
    {
      "cover": "https://miro.medium.com/max/700/1*_HOPHwvCXD3oXQ2Q06wnjQ.jpeg",
      "title": "The More Normal Things Get, the Weirder Life Feels",
      "summary": "We’ve reached the uncanny valley phase of the pandemic",
      "user": "Kelli María Korducki",
      "section": "Forge",
      "date": "9/16/2020",
      "time": "4",
      "popular": "No",
      "ranking": 635,
      "editorPick": "No",
      "mediumLink": "https://forge.medium.com/the-more-normal-things-get-the-weirder-life-feels-3530ab9b0e76"
    },
    {
      "cover": "https://miro.medium.com/max/1000/1*I7hJJ6AS4tYmYq_SjKf1Jg.jpeg",
      "title": "The 3 Breaks You Need to Take Every Day",
      "summary": "An easy strategy for being happier and more productive at work",
      "user": "Laura Vanderkam",
      "section": "Forge",
      "date": "9/16/2020",
      "time": "3",
      "popular": "No",
      "ranking": 506,
      "editorPick": "No",
      "mediumLink": "https://forge.medium.com/the-3-breaks-you-need-to-take-every-day-44b84e062086"
    },
    {
      "cover": "https://miro.medium.com/max/700/1*8WuEf2WT_HC1zXlNbfozaQ.jpeg",
      "title": "‘Ugh’ Tasks: Why Basic Items on Your To-Do List Are Suddenly Insurmountable",
      "summary": "You flinch every time you remember that you still have to do them",
      "user": "Robert Wiblin",
      "section": "Forge",
      "date": "9/16/2020",
      "time": "5",
      "popular": "No",
      "ranking": 226,
      "editorPick": "No",
      "mediumLink": "https://forge.medium.com/ugh-tasks-why-basic-items-on-your-to-do-list-are-suddenly-insurmountable-8e9a7fe70ee4"
    },
    {
      "cover": "https://miro.medium.com/max/1000/1*LfINvDAvTth771msg7vfFA.jpeg",
      "title": "What Does Quarantine Even Mean Now?",
      "summary": "How we isolate is about our values, not just our health",
      "user": "Annaliese Griffin",
      "section": "Forge",
      "date": "9/16/2020",
      "time": "6",
      "popular": "No",
      "ranking": 211,
      "editorPick": "No",
      "mediumLink": "https://forge.medium.com/what-does-quarantine-even-mean-now-81835f7ab2b2"
    },
    {
      "cover": "https://miro.medium.com/max/700/1*Jbq7Rd1EfFRDt5eL1qyFSA.jpeg",
      "title": "A Low-Effort Way to Break an Anxious Rut",
      "summary": "What a concert pianist, a high-wire walker, and a hypnotherapist can teach you about getting unstuck",
      "user": "Ollivier Pourriol",
      "section": "Forge",
      "date": "9/16/2020",
      "time": "4",
      "popular": "No",
      "ranking": 142,
      "editorPick": "No",
      "mediumLink": "https://forge.medium.com/a-low-effort-way-to-break-an-anxious-rut-32ec632e816a"
    },
    {
      "cover": "https://miro.medium.com/max/700/1*OTaihH7-jMOETiqLu5zXyg.jpeg",
      "title": "9 Ways to Find Stillness in Turbulent Times",
      "summary": "Everyone from the Stoics to the Buddhists knew the importance of this essential virtue",
      "user": "Ryan Holiday",
      "section": "Forge",
      "date": "9/14/2020",
      "time": "6",
      "popular": "No",
      "ranking": 1200,
      "editorPick": "No",
      "mediumLink": "https://forge.medium.com/9-ways-to-find-stillness-in-turbulent-times-78725167b831"
    },
    {
      "cover": "https://miro.medium.com/max/700/1*rQ3GxkwX1lCEJJWIdtubdA.jpeg",
      "title": "4 Ways to Check in On Someone in a Non-Awkward Way",
      "summary": "",
      "user": "Ross McCammon",
      "section": "Forge",
      "date": "9/11/2020",
      "time": "2",
      "popular": "No",
      "ranking": 511,
      "editorPick": "No",
      "mediumLink": "https://forge.medium.com/4-ways-to-check-in-on-someone-in-a-non-awkward-way-dc2902f93a57"
    },
    {
      "cover": "https://miro.medium.com/max/700/1*hWJhLul87TcJspPLpLnLxw.png",
      "title": "A Life Lesson from the Kardashians (Even if You Can’t Stand the Kardashians)",
      "summary": "",
      "user": "Kelli María Korducki",
      "section": "Forge",
      "date": "9/11/2020",
      "time": "2",
      "popular": "No",
      "ranking": 521,
      "editorPick": "No",
      "mediumLink": "https://forge.medium.com/a-life-lesson-from-the-kardashians-even-if-you-cant-stand-the-kardashians-baef07985b07"
    },
    {
      "cover": "https://miro.medium.com/max/700/1*tSMI1wg6CySvNzNYFgXWCg.jpeg",
      "title": "Try a Silent Zoom Meeting",
      "summary": "",
      "user": "Cari Nazeer",
      "section": "Forge",
      "date": "9/11/2020",
      "time": "2",
      "popular": "No",
      "ranking": 474,
      "editorPick": "No",
      "mediumLink": "https://forge.medium.com/try-a-silent-zoom-meeting-98a5e8dbac4b"
    },
    {
      "cover": "https://miro.medium.com/max/700/1*XfRD7i5flhWbkVeD083bWQ.jpeg",
      "title": "How to Ethically Flake",
      "summary": "",
      "user": "Kara Cutruzzula",
      "section": "Forge",
      "date": "9/10/2020",
      "time": "5",
      "popular": "No",
      "ranking": 634,
      "editorPick": "No",
      "mediumLink": "https://forge.medium.com/how-to-ethically-flake-2b738fab6d58"
    },
    {
      "cover": "https://miro.medium.com/max/700/1*kRR92pOfmPN44EnAB6RgIQ.jpeg",
      "title": "We Can Abolish Language Policing",
      "summary": "Words can inspire reflection and growth, instead of prompting attacks",
      "user": "Devon Price",
      "section": "Human Parts",
      "date": "9/9/2020",
      "time": "15",
      "popular": "No",
      "ranking": 942,
      "editorPick": "No",
      "mediumLink": "https://humanparts.medium.com/we-can-abolish-language-policing-45ab2abf5688"
    },
    {
      "cover": "https://miro.medium.com/max/700/0*r5K58u1vO0DjAHy4.png",
      "title": "Reality Is Never Strange. We Are.",
      "summary": "Our expectations of the world are truly perplexing",
      "user": "More To That",
      "section": "Human Parts",
      "date": "9/15/2020",
      "time": "6",
      "popular": "No",
      "ranking": 1500,
      "editorPick": "No",
      "mediumLink": "https://humanparts.medium.com/reality-is-never-strange-we-are-1996cbe90692"
    },
    {
      "cover": "https://miro.medium.com/max/700/1*0X_88oONnrL_8I33rIwObA.jpeg",
      "title": "We’re All Quarantining With the Cool Girl",
      "summary": "I always wanted to be her, but now I’m not so sure",
      "user": "Sophia Wilson Pelton",
      "section": "Human Parts",
      "date": "9/6/2020",
      "time": "7",
      "popular": "No",
      "ranking": 106,
      "editorPick": "No",
      "mediumLink": "https://humanparts.medium.com/quarantine-with-the-cool-girl-659d4fb85e2c"
    },
    {
      "cover": "https://miro.medium.com/max/2160/0*JZhZgd3J7B672s--.gif",
      "title": "Free Will Astrology, Week of September 17",
      "summary": "Weekly horoscopes from astrologer Rob Brezsny",
      "user": "Rob Brezsny",
      "section": "Human Parts",
      "date": "9/16/2020",
      "time": "7",
      "popular": "No",
      "ranking": 54,
      "editorPick": "No",
      "mediumLink": "https://humanparts.medium.com/free-will-astrology-week-of-september-17-d496fc60e6cf"
    },
    {
      "cover": "https://miro.medium.com/max/700/1*Rx_SbkL-bZSDG01lpLmwwg.jpeg",
      "title": "The Spiritual Principles Getting Me Through Remote School",
      "summary": "Balance is dead — instead, we must learn to tilt",
      "user": "Lisa Marie",
      "section": "Human Parts",
      "date": "9/15/2020",
      "time": "8",
      "popular": "No",
      "ranking": 142,
      "editorPick": "No",
      "mediumLink": "https://humanparts.medium.com/how-to-find-grace-when-school-is-at-home-fddfff35f1bc"
    },
    {
      "cover": "https://miro.medium.com/max/700/1*jXMIdjwqDO4Ly-vkpXfDYA.jpeg",
      "title": "A Normal Child",
      "summary": "Parents aren’t perfect. And neither are children.",
      "user": "Alexandro Chen",
      "section": "Human Parts",
      "date": "9/11/2020",
      "time": "8",
      "popular": "No",
      "ranking": 652,
      "editorPick": "No",
      "mediumLink": "https://humanparts.medium.com/a-normal-child-3d3117cd39a9"
    },
    {
      "cover": "https://miro.medium.com/max/700/1*1jveLJct79tjje9dOltWGA.jpeg",
      "title": "Who we were on 9/11",
      "summary": "",
      "user": "Human Parts",
      "section": "Human Parts",
      "date": "9/11/2020",
      "time": "3",
      "popular": "No",
      "ranking": 424,
      "editorPick": "No",
      "mediumLink": "https://humanparts.medium.com/who-we-were-on-9-11-334d2ee50ad0"
    },
    {
      "cover": "https://miro.medium.com/max/700/1*PZwgIvjt9i2kl8IymnPBmw.jpeg",
      "title": "Quarantine Has Forced Me to Confront How Little I Care About Myself",
      "summary": "My sustained lack of motivation has forced me to question what that motivation was made of in the first place",
      "user": "Emily J. Smith",
      "section": "Human Parts",
      "date": "9/8/2020",
      "time": "7",
      "popular": "No",
      "ranking": 6900,
      "editorPick": "No",
      "mediumLink": "https://humanparts.medium.com/quarantine-has-forced-me-to-confront-how-little-i-care-about-myself-2ef7687a986c"
    },
    {
      "cover": "https://miro.medium.com/max/700/1*tIynCQ_pXzUn922kdy_cvQ.jpeg",
      "title": "Consent Is a Living Thing, Not a Word",
      "summary": "Navigating yes, no, and the sticky spots in between",
      "user": "Madeline Berky",
      "section": "Human Parts",
      "date": "9/8/2020",
      "time": "18",
      "popular": "No",
      "ranking": 363,
      "editorPick": "No",
      "mediumLink": "https://humanparts.medium.com/consent-is-a-living-thing-not-a-word-a995dfd69cd8"
    },
    {
      "cover": "https://miro.medium.com/max/700/1*c65VY6zmAJFSpvt5U1FNeg.jpeg",
      "title": "How Slack Became Boring",
      "summary": "In the war for the remote office, why isn’t the hyped messaging app pulling a Zoom?",
      "user": "Rob Walker",
      "section": "Maker",
      "date": "9/16/2020",
      "time": "5",
      "popular": "No",
      "ranking": 838,
      "editorPick": "No",
      "mediumLink": "https://marker.medium.com/how-slack-became-boring-5af5369e609f"
    },
    {
      "cover": "https://miro.medium.com/max/700/1*bhXFDFs6ROB0CYhClxrJsQ.png",
      "title": "We’re Eating More and Smoking Less, According to Our Trash",
      "summary": "Turning our beaches into a receptacle for Big Plastic",
      "user": "Marker Editors",
      "section": "Maker",
      "date": "9/16/2020",
      "time": "2",
      "popular": "No",
      "ranking": 31,
      "editorPick": "No",
      "mediumLink": "https://marker.medium.com/how-food-wrappers-dethroned-cigarette-butts-as-the-most-common-beach-trash-by-the-numbers-225f22be09ed"
    },
    {
      "cover": "https://miro.medium.com/max/700/1*dhrTdohSkotgTvM_rs8_uw.png",
      "title": "America’s Penny Problem, by the Numbers",
      "summary": "Amid a national coin shortage, nearly half the U.S. wants the penny gone",
      "user": "Marker Editors",
      "section": "Maker",
      "date": "9/16/2020",
      "time": "2",
      "popular": "No",
      "ranking": 246,
      "editorPick": "No",
      "mediumLink": "https://marker.medium.com/americas-penny-problem-by-the-numbers-4ca4a2eff57f"
    },
    {
      "cover": "https://miro.medium.com/max/700/1*yvcba73uNhymkIVHx-T6_g.png",
      "title": "The End of the High School Vaping Boom, by the Numbers",
      "summary": "We have passed peak Juul",
      "user": "Marker Editors",
      "section": "Maker",
      "date": "9/15/2020",
      "time": "2",
      "popular": "No",
      "ranking": 157,
      "editorPick": "No",
      "mediumLink": "https://marker.medium.com/the-end-of-the-high-school-vaping-boom-by-the-numbers-a3eb9820739b"
    },
    {
      "cover": "https://miro.medium.com/max/700/1*yzLoVD7zJVViEaVvLjEKnQ.jpeg",
      "title": "Will Apple Ever Choose India Over China?",
      "summary": "As the pandemic pushes the tech giant to diversify its supply chain, India is eager to take up the mantle",
      "user": "Sarvesh Mathi",
      "section": "Maker",
      "date": "9/15/2020",
      "time": "9",
      "popular": "No",
      "ranking": 394,
      "editorPick": "No",
      "mediumLink": "https://marker.medium.com/will-apple-ever-choose-india-over-china-2ea5a4fad886"
    },
    {
      "cover": "https://miro.medium.com/max/700/1*JXDfFiua4HU3f_NLQYEFEw.png",
      "title": "The Cost of the Infamous Virus-Spreading Motorcycle Rally",
      "summary": "A stark reminder that public health precautions and economic outcomes are in alignment, not conflict",
      "user": "Marker Editors",
      "section": "Maker",
      "date": "9/14/2020",
      "time": "2",
      "popular": "No",
      "ranking": 422,
      "editorPick": "No",
      "mediumLink": "https://marker.medium.com/the-cost-of-the-infamous-virus-spreading-motorcycle-rally-862d12d42d6"
    },
    {
      "cover": "https://miro.medium.com/max/700/1*UFxAvXElNDA80J5cxY052Q.jpeg",
      "title": "How Uber and Airbnb Created a Parasite Economy",
      "summary": "An examination of more than a dozen companies reveals the nuances between gig platforms and their workers",
      "user": "Kaushik Viswanath",
      "section": "Maker",
      "date": "9/14/2020",
      "time": "12",
      "popular": "No",
      "ranking": 691,
      "editorPick": "No",
      "mediumLink": "https://marker.medium.com/uber-and-airbnb-are-parasites-but-they-dont-have-to-be-36909355ac3b"
    },
    {
      "cover": "https://miro.medium.com/max/1000/1*kcS74HqZbQbp-lMZJTkqEA.jpeg",
      "title": "As California Burns, People’s Market Makes Room for Everyone",
      "summary": "This San Pablo market and liquor store is vital to the immigrant community it serves",
      "user": "Alan Chazaro",
      "section": "Level",
      "date": "9/17/2020",
      "time": "5",
      "popular": "No",
      "ranking": 481,
      "editorPick": "No",
      "mediumLink": "https://level.medium.com/as-california-burns-peoples-market-makes-room-for-everyone-382f73b9c6ff"
    },
    {
      "cover": "https://miro.medium.com/max/700/1*Y4Hd7aXMxTBXVpTHgJ4wsQ.jpeg",
      "title": "It’s Not Polls We Distrust — It’s White People",
      "summary": "No matter how much of an advantage Biden seems to have, we’ve been through this before",
      "user": "David Dennis, Jr.",
      "section": "Level",
      "date": "9/16/2020",
      "time": "4",
      "popular": "No",
      "ranking": 779,
      "editorPick": "No",
      "mediumLink": "https://level.medium.com/its-not-polls-we-distrust-it-s-white-people-71b809dea496"
    },
    {
      "cover": "https://miro.medium.com/max/700/1*iB-JetknYavXSYT7-6Wo3A.jpeg",
      "title": "6 Best Ways To Discipline Your Kids Without Putting Hands on Them, Ranked",
      "summary": "Go get the (Nintendo) Switch!",
      "user": "LEVEL Editors",
      "section": "Level",
      "date": "9/16/2020",
      "time": "3",
      "popular": "No",
      "ranking": 139,
      "editorPick": "No",
      "mediumLink": "https://level.medium.com/6-best-ways-to-discipline-your-kids-without-putting-hands-on-them-ranked-b2796524fe8d"
    },
    {
      "cover": "https://miro.medium.com/max/700/1*AhpGLed4UqVIsdx78-5Zew.jpeg",
      "title": "Black Thought Is Loved and Feared by Your Favorite Rapper",
      "summary": "The Roots’ frontman talks continuously improving as a man and MC",
      "user": "Bonsu Thompson",
      "section": "Level",
      "date": "9/16/2020",
      "time": "12",
      "popular": "No",
      "ranking": 305,
      "editorPick": "No",
      "mediumLink": "https://level.medium.com/black-thought-is-loved-and-feared-by-your-favorite-rapper-89e179cf3b3f"
    },
    {
      "cover": "https://miro.medium.com/max/1000/1*ZRRqvgU8ANYCXGQHuVn42Q.jpeg",
      "title": "Amid a Pandemic and Racial Reckoning, Atlanta’s Corner Stores Are Community Cornerstones",
      "summary": "When Carver Neighborhood Market was vandalized earlier this year, patrons rallied to support the grocer that offers fresh produce in one of Atlanta’s food deserts",
      "user": "Jewel Wicker",
      "section": "Level",
      "date": "9/16/2020",
      "time": "6",
      "popular": "No",
      "ranking": 193,
      "editorPick": "No",
      "mediumLink": "https://level.medium.com/amid-a-pandemic-and-racial-reckoning-atlantas-corner-stores-are-community-cornerstones-edf47a730ecb"
    },
    {
      "cover": "https://miro.medium.com/max/700/0*E_63TdeUgSTranC4",
      "title": "12 Ways to Build Delicious Veggie Burgers",
      "summary": "Start with this bean burger recipe and go from there",
      "user": "Mark Bittman",
      "section": "Heated",
      "date": "9/17/2020",
      "time": "4",
      "popular": "No",
      "ranking": 39,
      "editorPick": "No",
      "mediumLink": "https://heated.medium.com/12-ways-to-build-delicious-veggie-burgers-606edb678e85"
    },
    {
      "cover": "https://miro.medium.com/max/700/1*VUQWUGmihrbsEH2lYUIXcw.jpeg",
      "title": "Your Best Pasta All Year May Be This Raw and Cooked Tomato Combo",
      "summary": "Now’s the time to make it",
      "user": "Edward Schneider",
      "section": "Heated",
      "date": "9/17/2020",
      "time": "3",
      "popular": "No",
      "ranking": 4,
      "editorPick": "No",
      "mediumLink": "https://heated.medium.com/your-best-pasta-all-year-may-be-this-raw-and-cooked-tomato-combo-538b526cd780"
    },
    {
      "cover": "https://miro.medium.com/max/1000/1*6d86ZgnXuaZV6UxWVYWBfw.jpeg",
      "title": "The Problem With ‘The 101 Best Pizzas in America’",
      "summary": "Your local pizza spot is enough, especially when it needs your support more than ever",
      "user": "Sara Pepitone",
      "section": "Heated",
      "date": "9/15/2020",
      "time": "3",
      "popular": "No",
      "ranking": 72,
      "editorPick": "No",
      "mediumLink": "https://heated.medium.com/the-problem-with-the-101-best-pizzas-in-america-161dbb7f48a4"
    },
    {
      "cover": "https://miro.medium.com/max/1000/1*21r3rkrPk-1ARVK46A-a-A.jpeg",
      "title": "The Covid-19 Story Behind Your Wild-Caught Salmon",
      "summary": "The world’s largest sockeye fishery evades the pandemic, but another disaster looms",
      "user": "betsy Andrews",
      "section": "Heated",
      "date": "9/15/2020",
      "time": "16",
      "popular": "No",
      "ranking": 45,
      "editorPick": "No",
      "mediumLink": "https://heated.medium.com/the-covid-19-story-behind-your-wild-caught-salmon-89517223ff32"
    },
    {
      "cover": "https://miro.medium.com/max/700/0*2xPqkZTFzhP1zfPo",
      "title": "24 Glorious Ways to Cook Eggs",
      "summary": "You will never get bored of them",
      "user": "Mark Bittman",
      "section": "Heated",
      "date": "9/14/2020",
      "time": "5",
      "popular": "No",
      "ranking": 456,
      "editorPick": "No",
      "mediumLink": "https://heated.medium.com/learn-how-james-beard-cooked-scrambled-eggs-plus-23-more-egg-recipes-6d557e97a9f8"
    }
]

let massivePost = ()=>{
    testArray.forEach( post => {
        $.ajax({
            url: "https://ajaxclass9g.firebaseio.com/bell/medium/posts/.json",
            method: "POST",
            data: JSON.stringify(post),
            success: (response) => {console.log(response)},
            async: false 
        })
    })
}

massivePost()*/


